### ISSUE TITLE
no phenotypes for MS?

### ISSUE THREAD

**Issue by oneilsh** [monarch-initiative/monarch-py#108]
https://api-v3.monarchinitiative.org/v3/api/association/all?category=biolink%3ADiseaseToPhenotypicFeatureAssociation&entity=MONDO:0005301&limit=10&offset=0

**Comment by monicacecilia** [comment]
Hi @oneilsh.
Yes, you are correct. No phenotype associations exist for this Mondo term or any of its children. The Monarch KG is displaying this correctly. 
Please let us know if we can help with additional information. 

@sabrinatoro 👀 👆 FYI.
