### ISSUE TITLE
Add SQLite implementation

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-py#13]
- [x] Use pystow to manage downloading and hold on to the sqlite database
- [x] implement entity interface
- [x] implement association interface

**Comment by glass-ships** [comment]
- [ ] Document CLI usage 
- [ ] Document SQL Implementation

**Comment by glass-ships** [comment]
One nitpicky edit I could make is to do a try for all values in case any are missing (in sql entity), the same way i do for source. but i can't imagine it's super critical. 

also this PR didn't bump the version for release (my bad)

**Comment by kevinschaper** [comment]
Hopefully once we're using the linkml dumper, it will be less of an issue, since everything will sync on the same linkml schema.  I can bump the version number in #27 and bring that in today
