### ISSUE TITLE
Make Rich tables for interactive association listing

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-py#15]
I brought in Rich as a dependency to get prettier cli output, but we can take that an extra step by using Rich's table 
functionality https://rich.readthedocs.io/en/stable/tables.html

**Comment by glass-ships** [comment]
Being looked at in #48 

Prettier output is possible, though I'm not sure how interactive we can make it. 

Actually, maybe utilizing a Rich prompt of some kind to ask the user which columns to include?

**Comment by glass-ships** [comment]
This is pretty much done as is. 

We should make a new issue if/when we decide to allow for a user-specified / pre-defined subset of columns
