### ISSUE TITLE
Publish monarch-py sphinx documentation

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-py#25]
If you retrofit this repo to @hrshdhgd's cookiecutter (which is part of our bbop best practice which I'd like to make monarch best practice)

https://github.com/hrshdhgd/sphintoxetry-cookiecutter

Then you will end up with github actions that will auto-publish sphinx docs derived from your docstrings on GH pages

**Comment by kevinschaper** [comment]
Can we consider keeping the (I think?) equivalent functionality that we have implemented with MkDocs an mkdocstrings? On a totally subjective level, I find it easier to read than sphinx themes, but also the docs publishing process seems to be a lot less complicated. 

https://monarch-initiative.github.io/monarch-py/API-Reference/

Maybe a down side is that we need to explicitly include the code that we want to be represented in the docs?  (https://github.com/monarch-initiative/monarch-py/blob/main/docs/API-Reference/index.md)

**Comment by matentzn** [comment]
We are also using docstrings, but how are you dealing with click documentation? Afaics mkdocs only supports python docstring

**Comment by kevinschaper** [comment]
We do really need to add that. It looks like there's a mkdocs-typer, but it looks somewhat abondoned (https://pypi.org/project/mkdocs-typer/), there's an issue in the mkdocs-typer repo asking if it should be used, or if it makes more sense to get a click object from typer and use mkdocs-click instead...so it seems like there are a couple of options to try.

**Comment by glass-ships** [comment]
typer has this functionality built in actually, so I just made a PR #35 to add generating CLI docs to the make command. 
We can expand on this with more examples in a future pass
