### ISSUE TITLE
Set permissions on stow'd solr data dir

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-py#36]
When we use docker to serve solr, the directory that's mounted gets permissions set up with 

```
	chgrp --recursive 8983 $(SOLR_DATA_DIR)
	chmod --recursive g+w $(SOLR_DATA_DIR)
```

We should do this to the data directory that pystow installs. 

Ideally, we'd only run this after a download has happened (maybe check the state of a file if we don't know whether a download happened?)

If possible, this should be a windows compatible change too, though I'm not totally sure how that will work.

**Comment by glass-ships** [comment]
Addressed in #38
