### ISSUE TITLE
Add unit tests with mocking to (maybe) replace integration tests

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-py#9]
For TDD, it's really handy to write integration tests against a live Solr backend that has the whole KG loaded, but it's not necessarily practical, and not necessarily testing this codebase when it checks quantities. 

The tests really should be replaced so that they use mocking to confirm that that the right Solr query options are set, not that the right data is returned.

**Comment by kevinschaper** [comment]
I say "(maybe)" because the integration tests could still be handy for interactive development, though, it's hard to imagine they wouldn't eventually become a maintenance nightmare.

**Comment by glass-ships** [comment]
Taken care of: https://github.com/monarch-initiative/monarch-app/pull/203
